name: investments
description: Mobile app for investing

publish_to: "none"

version: 0.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  hive: ^2.2.3
  flutter_secure_storage: ^6.0.0
  http: ^0.13.5
  get_it: ^7.2.0
  flutter_native_splash: ^2.2.13
  crypt: ^4.2.1
  google_fonts: ^3.0.1
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: "app_icon"
  ios: true
  image_path: "assets/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/app_icon.png

  android_12:
    icon_background_color: "#FFFFFF"
    image: assets/app_icon.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
